### Ping
GET http://localhost:3003/

### Find Users
GET http://localhost:3003/users
Content-Type: application/json

{
    "email": "kathleenroberts@kpis.tech"
}

### Find Active Users
GET http://localhost:3003/users/active

### Find Inactive Users
GET http://localhost:3003/users/inactive